name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - mliberty1
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 0.9.11
        - 0.9.10
        - 0.9.9
        - 0.9.8
        - 0.9.7
        - 0.9.6
        - 0.9.5
        - 0.9.4
        - 0.9.3
        - 0.9.2
        - 0.9.1
        - 0.9.0
    validations:
      required: true
  - type: dropdown
    id: Environment
    attributes:
      label: What OS are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac OS X
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? And how to reproduce?
      placeholder: Tell us what you see!
      value: "Steps to reproduce + Description and expectation"
    validations:
      required: true
  - type: input
    id: Joulescope-SN
    attributes:
      label: Joulescope serial number
      description: Please copy serial number in back of Joulescope
